# Base image
FROM node:18

# App working directory
WORKDIR /app

# Copy dependencies
COPY . .
COPY apps/event ./apps/event
COPY libs ./libs

# Install dependencies & Build
RUN yarn install
RUN yarn build:event:dev

# Start app (dev or prod)
CMD ["yarn", "start:event:dev"]
