# Base image
FROM node:18

# App working directory
WORKDIR /app

# Copy dependencies
COPY . .
COPY apps/auth ./apps/auth
COPY libs ./libs

# Install dependencies & Build
RUN yarn install
RUN yarn build:auth:dev

# Start app (dev or prod)
CMD ["yarn", "start:auth:dev"]
